hackingmaterials/atomate

- matmethods/vasp/drones.py
- matmethods/vasp/firetasks/parse_outputs.py
- matmethods/vasp/tests/test_drones.py
- matmethods/vasp/tests/test_vasp_workflows.py
- matmethods/vasp/workflows/base/single_vasp.py
Major overhaul of the drone:
1. subclasses the AbstractDrone directly instead of the pymatgen-db vaspdrone. The drone overloads almost every single method from pymatgen-db drone anyway. 
2. Renamed it to VaspToDbtaskDrone(removed the leading 'MM')
3. added outcar to calc_reversed.x.output.outcar key. The drone filters and assimilites both vasprun.xml and outcar files.
4. post_process method is only for processing non-vasp generated files such as transformation.json and custodian.json
5. added more drone unittests
6. the 'completed_at' key seems to be working fine with the fe2o3 data send by @computron. But if you track the files using git, the time of modification for all the files become identical ==> str(datetime.datetime.fromtimestamp(os.path.getmtime(vasprun_file))) will return same …
> issue #12 fixes

- matmethods/tools/analysis.py
- matmethods/vasp/firetasks/parse_outputs.py
* `vasp.firetasks.parse_outputs.GibbsFreeEnergyTask`
- Changed the force constants to not be read when using `qha_type="debye_model"`. The Debye model version of the Gibbs free energy task would fail because the force constants were being read from the database documents, but they are not calculated when the Debye model is used and are not in the database.
* `tools.analysis.get_debye_model_gibbs`
- Changed number of elements in linspace to be `(t_max-t_min)/t_step +1` to have enough elements for a closed loop. I decided to keep `np.linspace` over `np.arange` to better support floating points.
- Return values for the function were changed to simply be lists rather than NumPy arrays. Arrays are not needed and are not properly converted to lists by `json.dumps`.
> Fix the Debye model GibbsFreeEnergyTask

- matmethods/vasp/firetasks/parse_outputs.py
* Previous changes moved the `force_constants` processing into another loop for phonon calculations to separate the processing from the Debye model. This broke the phonon post-processing because the `force_constants` were being appended to a list of outputs instead of applied to the ones that already existed. 
* Moving the `force_constants` processing back into the loop fixed this. 
* The solution is perhaps not the most elegant, but matches the style of existing code and has little duplicated code.
* Write tests with mocks for the analysis routines to make sure changing one thing does not break another. This is especially important for analysis tasks that have multiple modes such as phonon calculations and Debye calculations
* Think about how to best check for the `qha_type`. I think we …
> Fix phonon calculation analysis

- matmethods/vasp/powerups.py
updating modify_to_soc and tag_fws powerups both tested and working
This powerup is for when a workflow is just defined and no previous calculations are available. For former case, current MatMethods SOC Firework should be modified to do both a static (with vasp_cmd) and nscf SOC (with vasp_ncl) so NBANDS MAGMOM are read from previous calculations
> updating modify_to_soc and tag_fws powerups both tested and working 

- matmethods/vasp/powerups.py
just a small change. Now static also runs w/o SOC and vasp_ncl; only nscf jobs run with vasp_ncl.
> running structure and static w/o SOC

- atomate/vasp/workflows/base/deformations.py
- atomate/vasp/workflows/base/elastic.py
- atomate/vasp/workflows/presets/core.py
- atomate/vasp/workflows/tests/test_elastic_workflow.py
@albalu pointed out a few discrepancies in calculated elastic constants and MP.  This PR should ensure that the MP workflow is replicated via the `wf_elastic_constant` in `vasp.workflows.presets.core`.  Also added a few lines to unit test to ensure that the relevant issue (i.e. vasp parameters) are verified.
> Minor changes to elastic workflow

- atomate/vasp/database.py
I may want to rebuild/update a collection (e.g. boltztrap + boltztrap DOS) but keep the old object ids and in a sense just update some of the documents w/o changing the ids, this small change to the code let me do that without changing its default functionality,
> add the ability to choose ObjectId in insert_gridfs

- atomate/vasp/builders/materials_ehull.py
- atomate/vasp/powerups.py
1. I implemented formation energy per atom in the Ehull builder before so it's tested but I forgot to merge it before.
2. users now have more control over tag_fws to tag the entire workflow and not just VaspRun jobs
> formation energy per atom in builder + more general tag_fws

- atomate/vasp/builders/tasks_materials.py
- atomate/vasp/firetasks/parse_outputs.py
- atomate/vasp/fireworks/core.py
- atomate/vasp/powerups.py
- atomate/vasp/tests/test_vasp_powerups.py
1. user can specify some tasks with excluded_tasks argument (a query) so they will be excluded when "materials" collection is being built. Examples of excluded_tasks is {"tags": "test"} or {"tags": {"$all": ["ABCD3", "soc"]}}
In the first example, I wouldn't want the "test" tasks to be included in the final materials collection and in the second one, I don't want the energy values of spin orbit coupling calculations for a specific projects to be included when say energy above hull is calculated.
2. now add_tags also tags Boltztrap jobs so organizing them would be easier later. A unit test is added but I also tested this on a bunch of bandstructure_boltztrap Wflows and the tags show up in the boltztrap collection.
> more control over materials builder + add_tags also through BoltztrapFW and BoltztrapToDBTask

- atomate/vasp/powerups.py
change the name of tag_fws to set_spec_fworker to avoid confusion with the add_tags powerup. Also the variable "tag" is renamed to fw_queuename to better reflect the goal of this powerup. Please feel free to modify these names.
This change is backwards incompatible but I assume it has not been largely used. In my codes, at least, I can correct all the names later.
> change the name of tag_fws to set_fworker to avoid confusion

- scripts/mmwf
``mmwf`` requires MPRester to use the `-m` option, but it was not imported from pymatgen.
> Add import of MPRester to mmwf

- atomate/common/firetasks/tests/test_parse_outputs.py
Other tests were leaving task/counter collections that caused problems with the unit test
Fixed by clearing the whole test DB to ensure a clean run before starting the unit test
> Hopefully fixed the ToDBTask UnitTest once and for all

- atomate/common/firetasks/tests/test_parse_outputs.py
- atomate/vasp/workflows/tests/test_vasp_workflows.py
Python2 seems to complain without an __init__ for the test drone. Don't know why.
> Fix TestToDB under python2 and cleanup of MongoDB collections from testing

- scripts/atwf
Removing imports from `__init__.py` broke atwf. 
As an aside: I agree that `from [module] import *` all over the top level init is not useful, but I think we could put some commonly used things back. Anything user facing should go there, e.g. preset workflows, which become much less tedious to import.
> Fix broken import in atwf

- .travis.yml
- atomate/utils/testing.py
- atomate/vasp/firetasks/tests/test_write_vasp.py
- atomate/vasp/powerups.py
- atomate/vasp/test_files/bulk_modulus_wf/3/task.json
- atomate/vasp/test_files/bulk_modulus_wf/4/task.json
- atomate/vasp/test_files/bulk_modulus_wf/5/task.json
- atomate/vasp/test_files/bulk_modulus_wf/7/task.json
- atomate/vasp/tests/test_setup.py
- atomate/vasp/workflows/presets/core.py
- atomate/vasp/workflows/tests/test_adsorbate_workflow.py
- atomate/vasp/workflows/tests/test_bulk_modulus_workflow.py
- atomate/vasp/workflows/tests/test_elastic_workflow.py
- atomate/vasp/workflows/tests/test_neb_workflow.py
- atomate/vasp/workflows/tests/test_raman_workflow.py
- atomate/vasp/workflows/tests/test_vasp_workflows.py
- requirements-optional.txt
- requirements.txt
- setup.py
* Testing with python 2.7 fails on travis(3 is fine) due to numpy/scipy installation failure caused by some lapack issues. So i set up travis with conda(nothing fancy, straight up copied sample config from conda doc with minor customizations) for both 2.7 and 3.6
* All tests except one pass for both 2.7 and 3.6. The only test that keep failing is the bulk modulus wflow test(some pymongo issue on travis) but it passes on my machine(both 2.7 and 3.6).  @albalu could you take a look at the bulk modulus tests?  Also i noticed that in the bulk modulus test some of the refernce files are getting modified?!
> Fix travis and misc cleanup of tests

- atomate/vasp/workflows/base/library/dielectric_constant_no_opt.yaml
Previously yaml definition didn't include copy_vasp_outputs which is set by default to True in the LepsFW. This just ensures it gets set to false since there is no previous firework.
> Fixed dieletric_constant_no_opt

- atomate/vasp/drones.py
- atomate/vasp/tests/test_drones.py
This simply adds information to `calcs_reversed` on what volumetric data is present for easier querying of the tasks collection.
This doesn't address *how* we may one day want to store the volumetric data itself (#139), which is a much larger question.
@tschaume is using the Atomate drone on large set of tasks soon, so this (or something like it) would be useful to have for that, to save having to re-run it later.
> Small change to VaspDrone to pick up volumetric data metadata

- atomate/vasp/firetasks/parse_outputs.py
- atomate/vasp/workflows/base/gibbs.py
- atomate/vasp/workflows/presets/core.py
The QuasiharmonicDebyeApprox was updated in pymatgen to support adding the anharmonic part of the vibrational free energy to the Debye model.
A new version of pymatgen has been released with these changes and this PR adds that functionality here.
This includes a small change allowing deformations to be customized in the preset workflow as well as whether to include the anharmonic contribution, but leaves all of the defaults unchanged.
**Note: depends on #145. Please merge that first!**
> Add anharmonic support to Gibbs free energy workflow

- atomate/vasp/powerups.py
- scripts/atwf
* atwf now supports modifying workflows that have been added to the database in place.
* Also adds a clear_modify powerup in case you want to remove all of your modify_incar/modify_potcar powerups to start anew.
* Fixes a bug in the testing framework to submit a test workflow for NEBs.  As of now, I haven't verified that this NEB workflow will execute successfully.
Examples:
```
$ atwf powerup -i 1 -n add_modify_incar
$ atwf powerup -q '{"name": {"$regex": "Si"}}' -n add_modify_incar 
-pk '{"modify_incar_params":{"incar_update": {"ENAUG": 2000}}}'
$ atwf powerup -i 1 -n clear_modify
$ atwf powerup --help
>>> usage: atwf powerup [-h] [-i WF_ID] [-q QUERY] [-n NAME] [-m MODULE]
[-pk POWERUP_KWARGS]
optional arguments:
-h, --help            show this help message and exit
-i WF_ID, --wf_id …
```
> Atwf update

- atomate/vasp/drones.py
copy piezo tensor to output in drone
checks to ensure the structure is non-centrosymmetric
useful to move this to output for easier searching
Also considering adding a non-centrosymmetric tag to the spacegroup, but not sure if that makes sense
> copy piezo tensor to output if applicable

- atomate/vasp/firetasks/run_calc.py
- atomate/vasp/fireworks/core.py
Updating the optimization per #19 
Switched ediffg to default to -0.05
changed default to not include MaxForceErrorHandler 
add in half_kpts_first_relax and set to default to true
Currently, we use double relaxations. Would it make sense to switch to full opt since that enables the 2% vol change check @shyuep recommends? Does this primarily mitigate issues with Pulay stresses?
In reference to @montoyjh's suggestion of looking into the FFT  grid size, I ran some test calculations of GGA+U and SCAN optimizations for Si, Fe, Al2O3, Fe2O3, and GaN after rattling all atoms + one significant perturbation. In all cases setting ENAUG to 4*ENCUT was as at minimum 7% faster average over 4 tries, and in some cases as much as 54% faster. The resulting structures and energies all matched with the …
> New optimization scheme

- atomate/vasp/drones.py
- atomate/vasp/tests/test_drones.py
Fixed a bug in the drone for parsing runs with IBRION==1 where VASP fails to output efermi
Added in logic to determine if a run is uniform or line for nscf calculations and create the right type of Bandstructure class
> Update Bandstructure parsing in Drone

- atomate/vasp/drones.py
Atomate drone has seen a few changes recently, and version number isn't always changed when the schema changes. Makes sense to me just to track the schema with the atomate version instead?
> Proposal: change schema version to match atomate version

- atomate/common/firetasks/glue_tasks.py
- atomate/vasp/firetasks/glue_tasks.py
- atomate/vasp/firetasks/tests/test_get_interpolated_poscar.py
GetInterpolatedPOSCAR get's the CONTCAR from a two previously run FireWorks and writes a specified interpolated structure as POSCAR.
The modification made to CopyVaspOutputs prevents moving CONTCAR->POSCAR if CONTCAR is included in additional_files and "contcar_to_poscar"=False.
> Added GetInterpolatedPOSCAR + test and modified CopyVaspOutputs. (pull request 2/5)

- atomate/vasp/firetasks/run_calc.py
- atomate/vasp/powerups.py
- requirements.txt
Changes
1. Little powerup that sets _preserve_fworker
Useful for those of us who spend a few hours writing code to do just this and then realize the 
functionality was already there......
2. Included DriftErrorHandler when ediffg is set.
> Powerup to Preserve Fworker  and include DriftErrorHandler

- atomate/vasp/drones.py
- atomate/vasp/tests/test_drones.py
Simple addition to the VASP drone to parse LOCPOT and save the axis averages which can be used for surface and defect corrections. 
Currently defaults to not parse, but can very easily change to parse by default since it's a tiny amount of data that might be useful for other things?
> Parse LOCPOT

- atomate/vasp/fireworks/core.py
apply vasp_input_set_params when StaticFW have parents
> current StaticFW will not apply vasp_input_set_params when have parents
> apply vasp_input_set_params when StaticFW have parents

- atomate/common/firetasks/glue_tasks.py
- atomate/utils/fileio.py
1) two args "name_prepend", "name_append" were coded to be optional but listed as required parameters.
2) added optional arg "keep_filenames" that is necessary if copying from subfolders. I may need this in subsequent AmsetFW PR. keep_filenames defaults to False so it is backwards-compatible. Please feel free to revert this commit if there's an issue with this.
> optional parameters in CopyFilesFromCalcLoc

- atomate/common/firetasks/glue_tasks.py
- atomate/utils/fileio.py
- requirements.txt
- setup.py
- This brief PR is to address issue #193 to use boltons.fileutils.copytree instead of a previously custom defined copytree functions from shutil library. This has been tested with the '$ALL' option where copytree is actually called.
- boltons is added to requirements.txt and setup.py
> use boltons.fileutils.copytree instead of the custom made copytree

- atomate/common/firetasks/glue_tasks.py
- requirements.txt
- setup.py
Used monty.shutil.copy_r instead of boltons.fileutils.copytree to remove boltons from requirements as it was the only use of boltons package at the moment.
> use monty.shutil.copy_r instead of boltons.fileutils.copytree

- atomate/vasp/drones.py
- atomate/vasp/firetasks/parse_outputs.py
Primarily to fix a bug where some basic bandgap properties weren't being copied to the root output document because is_metal wasn't present in the calculation's output. 
- Added some additional comments along the way
- Removed compress_bs and compress_dos, since those didn't actually do anything and the DB is responsible for compressing them.
> Drone Updates

- README.md
```
Traceback (most recent call last):
File "setup.py", line 15, in <module>
long_description=open(os.path.join(module_dir, 'README.md')).read(),
File "/global/u1/m/matcomp/mp_prod_atomate/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 912: ordinal not in range(128)
```
> wrong dash breaks `python setup.py develop`

- atomate/vasp/drones.py
- atomate/vasp/workflows/tests/test_vasp_workflows.py
If a user specifies an "additional_fields" kwarg to VaspToDb that's MSONable, fireworks serializes and deserializes the object, but the vasp drone doesn't, so when it's inserted into mongo or the json output, it's cast to a string, rather than an as_dict representation of the object.  This PR fixes by using jsanitize to recursively cast "additional_fields" to json at the beginning of the VASP output analysis.
> Small fix to additional_fields bug

- atomate/feff/firetasks/parse_outputs.py
- atomate/lammps/drones.py
- atomate/utils/database.py
- atomate/vasp/drones.py
We're using datetime.utcnow() in most places and datetime.today() (which returns local system time without tz info) in some drones.  This PR changes all of those to datetime.utcnow().
> update datetime.today to datetime.utcnow

- atomate/lammps/drones.py
- atomate/lammps/firetasks/__init__.py
- atomate/lammps/firetasks/run_calc.py
- atomate/lammps/firetasks/write_inputs.py
- atomate/lammps/fireworks/__init__.py
- atomate/lammps/fireworks/core.py
- atomate/lammps/tests/test_drone.py
- atomate/lammps/workflows/__init__.py
- atomate/lammps/workflows/core.py
- atomate/qchem/drones.py
- atomate/qchem/firetasks/run_calc.py
- atomate/qchem/firetasks/tests/test_run_calc.py
- atomate/qchem/firetasks/tests/test_write_inputs.py
- atomate/qchem/firetasks/write_inputs.py
- atomate/qchem/fireworks/tests/test_core.py
- atomate/qchem/test_files/co_qc.in
- atomate/qchem/test_files/to_opt.qin
- atomate/qchem/test_files/to_opt_pcm.qin
- atomate/qchem/tests/test_powerups.py
- atomate/qchem/workflows/tests/test_double_FF_opt.py
- atomate/qchem/workflows/tests/test_parse_pass_write.py
- atomate/qchem/workflows/tests/test_torsion_potential.py
- requirements.txt
I noticed that my other pull request suddenly included freshly broken tests after merging the latest updates to Atomate and changing the requirement to the newly released Pymatgen version. Thus I wanted to isolate those tests from my fragmentation code that remains under development. I also want to get the QChem refactor complete across the three repos. Thus, this pull request:
- Refactors QChem file names in Pymatgen and Custodian
- Updates the requirements to the latest Pymatgen release and the current Custodian master
We will likely want to wait to merge this until we have a stable Custodian release. But let's see if these few small changes break tests.
> Refactor QChem file names and update requirements

- atomate/utils/database.py
Previously no warning was issued if only read_only credentials were defined, leading to password not being set correctly. This leads to a confusing error message where `self.db.counter.find({"_id": "taskid"}).count()` fails due to an authentication error.
None
> Add sanity check to CalcDb.from_db_file

- atomate/vasp/workflows/base/elastic.py
Updates elastic workflow with updates to pymatgen codes, specifically
(i) changes pymatgen.analysis.elasticity.tensors to pymatgen.core.tensors
(ii) uses TensorMapping for symmetry reduction instead of deprecated accessor functions
Mostly this will no longer invoke the warnings, and should ensure forward compatibility of atomate.
> Update elasticity workflow for pymatgen elasticity updates

- atomate/vasp/workflows/base/library/bandstructure_no_opt.yaml
- atomate/vasp/workflows/presets/core.py
Adds a workflow to run a band structure without performing a structure optimization beforehand.
This workflow is a direct copy of the `wf_bandstructure` workflow, with the relaxation step removed.
Tagging @tschaume as he is interested in using this workflow.
> Add wf_bandstructure_no_opt workflow

- atomate/vasp/firetasks/run_calc.py
I was having errors with fireworks fizzling due to incorrect saving of the custodian.json.
Looks like the error was brought up in issue #262, but not corrected. This seems to be the agreed upon fix from the discussions.
> Fix custodian stored data (From issue #262)

- atomate/utils/database.py
Related to this issue:
https://groups.google.com/forum/#!topic/atomate/Q0ege6lPdqs
I had the same error. When I passed the database name into authsource it seemed to fix this issue.
<Short few sentences, and summary of the major changes in bullet 
points>
* Feature 1
* Feature 2
* Fix 1
* Fix 2
<If this is a work-in-progress, write something about what else needs 
to be done>
* Feature 1 supports a, but not b.
> Fixing db authentication error- update database.py

- atomate/utils/database.py
Currently, I'm running into issues connecting to MongoDB Atlas databases when loading a `VaspCalcDb` from a `db.json` file, because the `"authsource": "admin"` key is only used in the initialization of the `MongoClient` in `CalcDb.__init__()`. However, when the authentication is tested on line 45, the "authsource" kwarg is no longer used, resulting in a Authentication failure when the database is queried later (specifically at line 53). By checking if `kwargs` has an "authsource" key and passing the corresponding value - or the default source (`None`) if not - the problem is fixed.
As the credentials are now supplied in the initialization of the `MongoClient`since commit 02eb9a4932c18ef8155f8334a814bfc3d897bce2, is the `db.authenticate` line still necessary? In case it's only there to …
> fix: CalcDb: pass the authsource to db.authenticate

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs_rst/creating_workflows.rst
- docs_rst/index.rst
- docs_rst/installation.rst
The Atomate support forum is moving from Google Groups to Discourse (https://hackingmaterials.discourse.group/c/fireworks). I've updated all references to Google Groups to point to the new forum.
Once merged, the docs should be regenerated to reflect the updates.
> Update Google Groups references to Discourse

- atomate/vasp/powerups.py
- atomate/vasp/tests/test_vasp_powerups.py
Added a powerup that allows the `walltime`, `time_min`, and `qos` queue submission options to be modified on a per-workflow basis. 
I did not make the powerup general (e.g., able to include arbitrary `SBATCH` arguments like number of nodes) because those changes would also require modification of the FWorker.
Tested and confirmed working on the Cori KNL queue. I'll note that I have only tested single-firework workflows.
> Add set_queue_options powerup

- .circleci/config.yml
Pull requests will now be tested against the latest Github versions of Pymatgen, custodian and fireworks. This is in addition to the existing tests against the latest versioned releases. This should make developing large changes that span multiple code bases somewhat easier.
Thanks @mkhorton and @rkingsbury
> Test github pymatgen, custodian, and fireworks versions

- atomate/vasp/firetasks/tests/test_write_vasp.py
- atomate/vasp/firetasks/write_inputs.py
- atomate/vasp/powerups.py
- atomate/vasp/tests/test_vasp_powerups.py
This was a useful feature for me, thought it might be useful for some other people.
Added the ModifyKpoints Firetask to modify a Kpoints object based on a dictionary that matches its attributes. Added an associated VASP powerup to do this at a workflow level.
> Add ModifyKpoints Firetask and associated VASP powerup

- .circleci/config.yml
Only run dev tests on pull requests, not the master branch.
> Disable dev tests on master branch

- atomate/vasp/config.py
We were storing volumetric data by default under the same logic as storing band structure data. These were only stored if explicitly generated. However, given typical database size restrictions, it would be better to turn this off by default and enable on-demand.
> Do not store volumetric data by default

- atomate/lammps/firetasks/run_calc.py
- atomate/lammps/fireworks/core.py
- atomate/lammps/workflows/core.py
Recent updates to the pymatgen `PackmolRunner` (see https://github.com/materialsproject/pymatgen/pull/1947) removed the `copy_to_current_on_exit` kwarg. This PR also removes the kwarg from `PackmolFW` and `RunPackmol`.
> remove retired copy_to_current_on_exit kwarg from PackmolFW

- atomate/vasp/firetasks/parse_outputs.py
- atomate/vasp/workflows/base/bulk_modulus.py
- atomate/vasp/workflows/base/deformations.py
- atomate/vasp/workflows/base/thermal_expansion.py
- atomate/vasp/workflows/presets/core.py
Fixes #445 
The `get_wf_bulk_modulus` and `get_wf_thermal_expansion` workflows assume that they will be appended to an OptimizeFW. If not, they fail because:
- They call `get_wf_deformations` with `copy_vasp_outputs=True`. Subsequently, when the deformation firework is run, there are no calc_locs in the firework spec to copy previous outputs from.
- The `FitEOSToDb` and `ThermalExpansionCoeffToDb` analysis FireTasks try and get the starting structure from a task with the `structure optimization` task label which doesn't exist in the workflow.
This PR addresses both issues by:
1. Adding a `copy_vasp_outputs` option to `get_wf_bulk_modulus` and `get_wf_thermal_expansion` which is passed through to the  `get_wf_deformations` and has a default value of `False`. 
2. Updating the analysis …
> Allow no optimization before bulk modulus/thermal expansion workflows

- atomate/vasp/firetasks/write_inputs.py
It has come to our attention that `Vasprun.get_band_structure().get_band_gap()["energy"]` can return an incorrect band gap in some cases. The bandgap is used to determine k-point density and smearing settings for SCAN calculations in `WriteScanRelaxFromPrev`. 
To make this firetask more robust, this PR switches the source of the bandgap information to `Vasprun.eigenvalue_band_properties[0]`.
> Change source of bandgap in SCAN workflow logic

- atomate/vasp/drones.py
- atomate/vasp/tests/test_drones.py
An additive change, to help diagnose issues where band gap might be reported inconsistently from a Vasprun.
> Add eigenvalue_band_properties to VASP drone

- atomate/common/powerups.py
- atomate/common/tests/test_powerups.py
- atomate/vasp/firetasks/electrode_tasks.py
- atomate/vasp/powerups.py
- atomate/vasp/tests/test_vasp_powerups.py
- atomate/vasp/workflows/base/electrode.py
- atomate/vasp/workflows/tests/test_insertion_workflow.py
- atomate/vasp/workflows/tests/test_raman_workflow.py
Minor rework of how powerups are discovered during dynamic workflows.
- the `powerup_by_kwargs` function now has a sequence of the modules where it will look for powers (similar to a path variable)
- the user can also provide new modules that contain additional powerups using the `add_powerup_module` flag
- If a powerup is found, in any module, apply that powerup and stop looking
> better handling of dynamic powerups

- atomate/vasp/workflows/base/elastic.py
- atomate/vasp/workflows/presets/core.py
Correct VASP input params that causes large error in elastic tensors:
- Explicit set `LREAL=False` to override  MPRelaxSet default (`Auto`). `False` is recommended by VASP manual for small systems and high accuracy. 
- Remove `PREC=High` for static calculations, which is inconsistent with the relaxation job setting: `Accurate`.
> Correct VASP input for elastic workflow

- atomate/vasp/firetasks/electrode_tasks.py
Debug GetInsertionCalcs firetasks optimizefw_kwargs so user can provide override_default_vasp_params without conflicting with setting NSW=299 (if NSW is not set by the user)
See Insertion Worflow optimizefw_kwargs Issue for bug description:
[https://matsci.org/t/insertion-worflow-optimizefw-kwargs-issue/36593](https://matsci.org/t/insertion-worflow-optimizefw-kwargs-issue/36593)
> Insertion Worflow optimizefw_kwargs

- atomate/common/powerups.py
Changes the `add_namefile` common powerup to append the `fw.fw_id` to the namefile:
```diff
- fname = f"FW--{fw.name}"
+ fname = f"FW--{fw.name}-{fw.fw_id}"
```
> add_namefile include firework ID in file name

- atomate/vasp/firetasks/write_inputs.py
Current version of `WriteVaspFromIOSet` does not update the POSCAR using the `spec_structure_key` due to a bug on line 83 of `write_inputs.py`.
* Fix 1
`WriteVaspFromIOSet` does not correctly update the `vis` when `spec_structure_key` is set. The PR fixes the bug so the user-provided spec key can be passed.
> Fix bug in VASP IO write when `spec_structure_key` defined

- atomate/vasp/drones.py
- atomate/vasp/firetasks/absorption_tasks.py
- atomate/vasp/fireworks/absorption.py
* Added AbsorptionFW to run a frequency-dependent dielectric calculation, with two options: independent-particle approximation (IPA) and random-phase approximation (RPA). One can also specify a static run, but it will invoke the MPStaticSet rather than the AbsorptionSet. 
* Added absorption task to write input sets for these runs 
* Added a section in vasp drones to collect the dielectrics information from RPA calculation, and to calculate the corresponding absorption coefficient for easy access. 
* A typical usage of this FW would be : 
```
fw0 = OptimizeFW(structure)
fw1 = AbsorptionFW(mode = "STATIC", parent = fw0) # uses MPStaticSet
fw2 = AbsorptionFW(mode = "IPA", parent = fw1)   # uses AbsorptionSet supplied in pymatgen 
fw3 = AbsorptionFW(mode = "RPA", parent = fw2)  # uses …
```
> Absorption

- atomate/common/firetasks/glue_tasks.py
- atomate/vasp/firetasks/glue_tasks.py
This should fix the issue of the interpolation FW which currently does not find the CONTCAR file if its gzipped.
If the CONTCAR file is not gzipped, it still works fine.
More generally, this fix allows CopyFilesFromCalcLoc to decompress compressed file after copy if wanted.
This fix should solve previous raised issues (I can find them back now).
> Fix gzip contcar issue

- atomate/vasp/firetasks/tests/test_lobster_tasks.py
This is a fix for the Lobster task tests. This was necessary due to a recent change in pymatgen that I introduced myself (https://github.com/materialsproject/pymatgen/pull/2434).
> Fix Lobster Task Tests

- atomate/utils/tests/test_database.py
- atomate/vasp/workflows/tests/test_insertion_workflow.py
- requirements.txt
- setup.cfg
- fixed redundant code in insertion test
- changed from `boto3.client` to `boto3.resources` to better match what `maggma` does.  Also I was failing tests because it seems like the AWS API no longer liked me using `boto3.client.create_bucket` in the way this was originally written.
- Install attempts produced an error saying that have to choose a different `scipy` version (Ubuntu with python 3.9 and 3.10) so I bumped it to the nearest > version.
- Not super sure about the last one: but since we have turned off `qchem` tests on the GitHub workflows should we turn it off in `setup.cfg` as well?  It took a long time for me to figure out why all my tests were failing.
> small fixes to tests

- scripts/atwf
`atwf add POSCAR` errors out due to the `yaml.load` command here
The current version of `yaml.load` requires a `Loader` kwarg or just calling `safe_load` instead.
See here for more detail.
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
> atwf add POSCAR not working

- atomate/vasp/analysis/phonopy.py
- requirements.txt
- setup.py
I don't know the original version of `phonopy` that references the `_max_t_index` attribute but it appears they now use `self._len` in the same way: 
Examples:
https://github.com/phonopy/phonopy/blob/ac7abb7e4bbbd3e45d76d21cf3e722176830a9e1/phonopy/qha/core.py#L258
https://github.com/phonopy/phonopy/blob/ac7abb7e4bbbd3e45d76d21cf3e722176830a9e1/phonopy/qha/core.py#L263
The source of the `self._len` is listed below and should be the same as the `_max_t_index`.
```
self._num_elems = len(self._temperatures)
```
https://github.com/phonopy/phonopy/blob/ac7abb7e4bbbd3e45d76d21cf3e722176830a9e1/phonopy/qha/core.py#L364
----
```
beta = [0.0]
for i in range(1, self._num_elems - 1):
dt = self._temperatures[i + 1] - self._temperatures[i - 1]
dv = self._equiv_volumes[i + 1] - self._equiv_volumes[i - …
```
> Phonopy QHA fixed missing att

- atomate/common/powerups.py
Fix to remove the possibility of duplicate tags being added by the add_tags powerup. This was an issue with recursive workflows (such as get_ion_insertion_wf() which will apply powerup_by_kwargs() repeatedly) where the list of tags will grow with duplicate tag values.
> add_tags bug

- .github/workflows/combine_durations.py
- .github/workflows/test.yml
- .gitignore
- atomate/common/firetasks/tests/test_parse_outputs.py
- atomate/lammps/drones.py
- atomate/qchem/drones.py
- atomate/vasp/drones.py
- atomate/vasp/firetasks/lobster_tasks.py
- requirements-ci.txt
Following the initially longer than expected runtime of `pytest` in #734, I looked around a bit for a pytest plugin that would automatically distribute the workload among multiple concurrent runners.
Luckily, exactly such a thing exists. Never used it before but looks great.
https://github.com/jerry-git/pytest-split
And they even have a GHA demo:
https://github.com/jerry-git/pytest-split-gh-actions-demo/tree/master/.github/workflows
Let's see if I set this up correctly. :)
> use pytest-split in GHA test workflow

- atomate/common/firetasks/glue_tasks.py
- atomate/qchem/firetasks/tests/test_critic2.py
- atomate/vasp/analysis/phonopy.py
- atomate/vasp/drones.py
- atomate/vasp/firetasks/absorption_tasks.py
- atomate/vasp/firetasks/glue_tasks.py
- atomate/vasp/firetasks/tests/test_exchange.py
- atomate/vasp/fireworks/absorption.py
- atomate/vasp/workflows/tests/test_exchange_workflow.py
- atomate/vasp/workflows/tests/test_magnetism_workflow.py
Similar housekeeping PR as https://github.com/materialsproject/pymatgen/pull/2417/commits/a6f0a723c9087cd368b77e1183f260121e993349 and https://github.com/materialsproject/atomate2/pull/92 to replace the soon-to-be deprecated `monty.os.path.which` with standard library's `shutil.which`.
> From `monty` to `shutil` `which`

- atomate/qchem/firetasks/parse_outputs.py
- atomate/qchem/firetasks/run_calc.py
- atomate/qchem/fireworks/core.py
- atomate/qchem/fireworks/tests/test_core.py
- atomate/utils/tests/test_database.py
For this custom Firework the electronic energy of a proton in a specific solvent environment is approximated. Since a proton has 0 electrons, running a QChem job would yield an error. The energy can be approximated by:
* Calculating the energy of a hydrogen atom with 0 charge
* Calculating the energy of a system with a hydrogen atom (0 charge) and a proton separated at infinite distance 
* Subtracting the first energy from the second
This Firework combines these two calculations and adds a task doc to the DB with the separate calculation details and the effective energy after subtraction.
* Should be reviewed by @samblau before merge 
* Needs a CI test run.
> Add the firework for calculating the electronic energy of a proton in different solvent environments[WIP]

- .github/workflows/test.yml
- .pre-commit-config.yaml
- atomate/feff/workflows/tests/test_eels_workflows.py
- atomate/feff/workflows/tests/test_exafs_scattering_paths.py
- atomate/feff/workflows/tests/test_xas_workflows.py
- atomate/utils/testing.py
- atomate/vasp/analysis/linear_response.py
- atomate/vasp/firetasks/electrode_tasks.py
- atomate/vasp/firetasks/tests/test_polarization_to_db.py
- atomate/vasp/firetasks/tests/test_write_vasp.py
- atomate/vasp/fireworks/core.py
- atomate/vasp/fireworks/tests/test_fireworks_core.py
- atomate/vasp/fireworks/tests/test_nmr.py
- atomate/vasp/powerups.py
- atomate/vasp/workflows/tests/test_adsorbate_workflow.py
- atomate/vasp/workflows/tests/test_bulk_modulus_workflow.py
- atomate/vasp/workflows/tests/test_elastic_workflow.py
- atomate/vasp/workflows/tests/test_insertion_workflow.py
- atomate/vasp/workflows/tests/test_lobster_workflow.py
- atomate/vasp/workflows/tests/test_nmr.py
- atomate/vasp/workflows/tests/test_raman_workflow.py
- atomate/vasp/workflows/tests/test_vasp_workflows.py
- docs/_sources/running_workflows.rst.txt
- docs_rst/changelog.rst
- docs_rst/creating_workflows.rst
- docs_rst/installation.rst
- docs_rst/running_workflows.rst
- setup.cfg
- setup.py
Also
- changes `.github/workflows/test.yml` to use `setup-python` built-in dependency caching for GitHub actions
- updates broken `black` version used by `pre-commit` 
- bumps `actions/checkout` to v3, `actions/setup-python` to v4
> Fix `ModuleNotFoundError`: No module named 'pymatgen.transformations.defect_transformations'

- atomate/qchem/drones.py
Frequency calculations for single atoms may not have a `frequency_mode_vectors` key in their output, which was causing the Drone to fail parsing these calculations.
> QChemDrone: fix Frequency parsing for single atoms

- atomate/vasp/firetasks/tests/test_lobster_tasks.py
- atomate/vasp/workflows/tests/test_lobster_workflow.py
- requirements-ci.txt
- requirements.txt
#770 PR updated the pymatgen version in CI and requirements leading to failing lobster tests.
- Lobsterout parser keys in pymatgen has been updated > tests need to be updated accordingly
> updated lobster_tests with recent pymatgen changes
