matmethods/vasp/drones.py
matmethods/vasp/firetasks/parse_outputs.py
matmethods/vasp/tests/test_vasp_workflows.py

fix firetasks and unittests to reflect the recent changes to the schema
<If this is a work-in-progress, write something about what else needs 
to be done>
* Feature 1 supports a, but not b.

fix issues due to schema change

---

matmethods/vasp/input_sets.py
matmethods/vasp/tests/test_write_vasp.py

minor refactoring of ldau settings from previous incar

refactor ldau settings

---

matmethods/vasp/firetasks/write_inputs.py
matmethods/vasp/fireworks/core.py

Fix TransmuterStructure WF to be able to use structures from previous calc, e.g. force relaxations.

Transmuted structure from prev

---

docs/index.rst

Fixing some small typos as I read through the documentation.

Fixing small typos.

---

matmethods/vasp/builders/materials_ehull.py

I chose materials_ehull as it already calls Rester. Also, not sure if upsert is appropriate and whether ['N/A'] is necessary. I think it is more relevant to have this in tasks_materials.py but wasn't sure if I should call MPRester in that class so that I could use find_structure.

Just a test/practice for adding mpid to materials collection.

---

matmethods/vasp/fireworks/core.py

fixing MDWF after renaming. forgot to do this in the previous merge :)

fixing MDWF after renaming

---

matmethods/vasp/firetasks/parse_outputs.py
matmethods/vasp/workflows/base/bulk_modulus.py
matmethods/vasp/workflows/presets/core.py

Fit energies and volumes to the given equation of state
*  slightly modified gibbs wflow

Bulk modulus workflow

---

matmethods/vasp/firetasks/glue_tasks.py
matmethods/vasp/firetasks/parse_outputs.py
matmethods/vasp/workflows/base/deformations.py
matmethods/vasp/workflows/base/elastic.py

Minor fixes based on new deformation workflow structure and results of elasticity benchmarking
* added relaxation parameter to deformed workflow which sets IBRION=2 for static tasks if set
* fixes to strain passing and deformation enumeration in the elastic tasks

Dev elastic - minor fixes

---

matmethods/vasp/fireworks/core.py

Minor fix to enable Static FWs to use user-specified VIS, reversed the relevant `or` expression

Minor bug fix

---

requirements.txt
setup.py

This should fix the elastic tests.

Update requirements to fix elastic tests

---

atomate/vasp/firetasks/run_calc.py
atomate/vasp/fireworks/core.py

soc and scissor can be tuned directly in BoltztrapFW for better control.

previous pull request to add soc and scissor to Btrap FW

---

atomate/vasp/firetasks/run_calc.py

VaspFilesValidator to the validators of RunVaspCustodian Firetask. test_vasp_workflows ran w/o errors; does it need any additional tests?

adding VaspFilesValidator to RunVaspCustodian task

---

atomate/vasp/workflows/base/deformations.py
atomate/vasp/workflows/base/elastic.py
atomate/vasp/workflows/presets/core.py

Gives user the option to skip the initial optimization task in the elastic workflow. Preset to perform optimization first.

Adding the option to turn off initial structure optimization in elastic workflow.

---

atomate/vasp/config.py
atomate/vasp/powerups.py

Added gamma_vasp powerup using to fix #71 
Updated default configs to use env_check
Added in gamma_vasp to common powers

Update common powerups for vasp

---

atomate/vasp/firetasks/parse_outputs.py

* db_file is a required parameter so we put the result in db rather than printing to a .json file
* in addition to EOS data, the structure optimization data (+ FW tags) is passed to the "eos" collection to make further queries easier.
* bulk modulus in GPa will be available in the root of each document within the "eos" collection as all EOSs have the parameter b0 (b0 is in eV A^-3)
* a test for wf_bulk_modulus that has this task at the end
* I kept the name of the class FitEquationOfStateTask so it doesn't have ToDb in its name; not sure if that's a problem.
* the name "eos" is selected for the collection as it has more information than just the bulk modulus; feel free to modify it

modify FitEquationOfStateTask to insert the data to db rather than to .json

---

atomate/vasp/firetasks/parse_outputs.py

Reverts hackingmaterials/atomate#80

Revert "modify FitEquationOfStateTask to insert the data to db rather than to .json"

---

atomate/vasp/workflows/tests/test_adsorbate_workflow.py

A more reasonable unit test for the adsorption workflow

adsorption workflow

---

atomate/vasp/firetasks/parse_outputs.py
atomate/vasp/workflows/tests/test_elastic_workflow.py
requirements.txt

* Updates ElasticTensorToDb task to use new property dictionary functionality in new pymatgen
* Updates unit test
* Updates requirements.txt

Updates to elastic tensor workflow

---

docs/index.rst
docs/installation.rst

Improved documentation. Open to feedback and suggestions.
* Improved installation tutorial (beginner)
* Custom YAML workflows (beginner)
* Custom Python workflows (from existing Fireworks) (intermediate)
* Running workflows (from YAML library and Python) (beginner)
* Writing new Fireworks/Firetasks for workflows (machinery like envchk, powerups, passcalclocs) (advanced)
* Contributing - scope, separating concerns, code style guide, writing tests (intermediate)
If you have any feedback on my writing, organization of the docs, or planned documents (especially if you have ideas) please let me know.

Documentation: installation guide

---

atomate/common/firetasks/parse_outputs.py
atomate/common/firetasks/tests/test_parse_outputs.py

Parse output tests

---

atomate/common/firetasks/tests/test_parse_outputs.py

Fixed the unit test for ToDBTask
Addresses #101

Fixed TestToDbTask

---

atomate/vasp/firetasks/parse_outputs.py
atomate/vasp/firetasks/write_inputs.py
atomate/vasp/workflows/base/deformations.py
atomate/vasp/workflows/tests/test_elastic_workflow.py

* Fix for elastic workflow without initial optimization, also added test to ensure that workflow runs without structure optimization.  Addresses #108 .
* Should also fix former todo where re-run initial optimizations won't necessarily be fed properly to analysis FW.

Elastic fix

---

docs/customizing_workflows.rst

Also fix indentation problems.
@computron you mentioned that you pushed the docs, but it doesn't look like the new release is up.

Fix docs by passing in the custom input set.

---

atomate/vasp/drones.py
scripts/atwf

Pulls the original inputs into the task document.

Process original inputs in vasp drone

---

atomate/vasp/firetasks/parse_outputs.py

Currently these collections are hard to search for specific structures because they create their own collections.
These changes make it somewhat easier to find calculations within collections.

Add pretty formulas to all *ToDb tasks

---

atomate/vasp/drones.py

…a percent
<Short few sentences, and summary of the major changes in bullet 
points>
* Feature 1
* Feature 2
* Fix 1
* Fix 2
<If this is a work-in-progress, write something about what else needs 
to be done>
* Feature 1 supports a, but not b.

Fix percent_delta_volume in vasp.drones.VaspDrone.set_analysis to be a percent

---

atomate/common/firetasks/glue_tasks.py
atomate/common/firetasks/tests/test_glue_tasks.py

This pull requests is in preparation for merging the ferroelectric workflow.
This specific pull requests adds the CreateFolder and GrabFilesFromCalcLoc classes and tests for these classes. Both of these classes will be used by the ferroelectric workflow.
GrabFilesFromCalcLoc may overlap with CopyFiles -- perhaps they should be merged?

Added CreateFolder and GrabFilesFromCalcLoc to common.firetasks.glue_… (pull request 1/5)

---

atomate/vasp/fireworks/core.py

DFPTFW requires force_gamma to be set to True. If one does not copy from a previous calculation and then DFPTFW previously broke from lack of forced gamma pt calculation.
* force_gamma feature for DFPTFW added
None.

force gamma in DFPTFW added

---

atomate/lammps/drones.py
atomate/lammps/firetasks/run_calc.py
atomate/lammps/firetasks/write_inputs.py
atomate/lammps/fireworks/core.py
atomate/lammps/tests/test_drone.py
atomate/lammps/tests/test_workflows.py
atomate/lammps/workflows/core.py
requirements.txt

* quick fix to conform with the latest pymatgen
* updated pmg req

lammps fix

---

atomate/vasp/database.py

"unpack" bandstructure and dos from GridFS (see code)

add find_task to complement insert_task

---

atomate/vasp/database.py

build dir_name index for queries in CalcDb.insert()

---

atomate/vasp/powerups.py

forward task_name_constraint to additional_fields

---

atomate/vasp/drones.py

The issue with the adsorption workflow is actually related to whether or not selective dynamics is included in determining whether the maximum force threshold is reached.  Presumably, if a VASP user has enabled selective dynamics (which appear as a site_property in the final structure of a parsed Vasprun), they don't want those forces which are ignored in the optimization included in the determination of max force, so I just filter the max force by selective dynamics if they're present in the final structure object site_properties.
Should address #203.

added fix for drones with selective dynamics criteria

---

scripts/atwf

make spec_path definition in atwf more robust

---

atomate/common/firetasks/tests/test_parse_outputs.py
atomate/utils/tests/db.json
atomate/utils/tests/test_utils.py
atomate/utils/utils.py

* Fixes get_database so that it works
* Add in tests for get_database and get_uri

Fix get_database

---

atomate/vasp/database.py
atomate/vasp/drones.py
atomate/vasp/firetasks/parse_outputs.py

Some updates for  the drone and db
- Removes force checking from the drone
- Stores task_id and compression metadata in GridFS for band structures and DOS

DB Updates

---

atomate/vasp/database.py
atomate/vasp/drones.py
atomate/vasp/firetasks/parse_outputs.py

Reverts hackingmaterials/atomate#223

Revert "DB Updates"

---

atomate/vasp/database.py
atomate/vasp/drones.py
atomate/vasp/firetasks/parse_outputs.py

Let's try this again.
Updates for DB insertion and Drone:
- switched to a single use_gridfs option for both Bandstructures and DOS
- cleaned up drone auto parsing for electronic structure
- fixed max force causing drone to set state to error (retain the max force analysis)

DB Update #2

---

atomate/vasp/firetasks/write_inputs.py

support list mutiply for ModifyIncar

support list mutiply for ModifyIncar

---

atomate/vasp/workflows/tests/test_adsorbate_workflow.py

Fix for the test referenced in #203.

adsorption fix

---

.circleci/config.yml

Remove coveralls.io coverage submission

Remove coveralls

---

atomate/vasp/database.py
atomate/vasp/drones.py
atomate/vasp/firetasks/parse_outputs.py
atomate/vasp/fireworks/core.py
atomate/vasp/tests/test_drones.py
atomate/vasp/workflows/tests/test_vasp_workflows.py
requirements.txt

* Added storage for CHGCAR type files.
* Added tests for CHGCAR and AECCAR storage
* Changed fireworks/core to allows kwargs to be passed for VaspToDb object

Chgcar storage

---

atomate/vasp/fireworks/core.py

This just updates those in core, I haven't changed these elsewhere.
Note this changes the default db_file from `None` to the value currently specified in config.py (`>>db_file<<`), if we want to keep the default as `None` I would suggest also changing the value in config.py, however I think this is fine as-is.

Change default vasp_cmd and db_file to those in config.py

---

atomate/vasp/workflows/base/magnetism.py

Ask Drone to store chgcars by default, remove old extraneous ToDb options.

Minor change to magnetic orderings wf

---

atomate/vasp/workflows/base/magnetism.py

A bad commit crept into master in the magnetism workflow; my apologies for that. This fixes the issue.

Magnetism bug fix

---

.circleci/config.yml
atomate/qchem/firetasks/fragmenter.py
atomate/qchem/tests/test_drones.py
requirements.txt

Update openbabel installation in circleCI testing.

Update openbabel requirement to match pymatgen

---

atomate/vasp/firetasks/lobster_tasks.py
atomate/vasp/powerups.py
atomate/vasp/workflows/base/lobster.py

Two small fixes so that the Lobster workflow works with "add_additional_fields_to_taskdocs".

fix lobsterworkflow to work with add_additional_fields_to_taskdocs

---

.pre-commit-config.yaml
atomate/utils/database.py
atomate/utils/tests/test_database.py
atomate/vasp/database.py

also used `black` on the test file

forgot to set key to fs_id for URI store

---

atomate/vasp/firetasks/electrode_tasks.py
atomate/vasp/workflows/base/electrode.py
atomate/vasp/workflows/tests/test_insertion_workflow.py

changed two parameters: attempt_insertions, max_inserted_atoms 
added documentation and tests

change the insertion wf params

---

atomate/vasp/firetasks/neb_tasks.py
atomate/vasp/fireworks/core.py
atomate/vasp/workflows/base/neb.py
atomate/vasp/workflows/tests/test_neb_workflow.py
requirements.txt

pymatgen diffusion has been changed to a namespace package `pymatgen.analysis.diffusion`
also there were some bare exceptions.

updated pymatgen-diffusion version

---

CONTRIBUTING.md
atomate/common/powerups.py
atomate/common/tests/test_powerups.py
atomate/vasp/firetasks/parse_outputs.py

Add common powerup add_metadata

---

atomate/vasp/workflows/base/electrode.py

Updated comment to include article citation.

added citation suggestion

---

atomate/vasp/powerups.py
atomate/vasp/tests/test_vasp_powerups.py

Ensure use_custodian() does not overwrite modify_gzip_vasp(wf, False)

---

atomate/vasp/analysis/linear_response.py
atomate/vasp/workflows/tests/test_hubbard_hund_linresp.py

A small PR that will help with one of the failing tests.
Also notifying @guymoore13.

Fix imports for pymatgen v2022

---

atomate/qchem/drones.py
atomate/utils/tests/test_utils.py
atomate/vasp/drones.py
atomate/vasp/firetasks/parse_outputs.py
atomate/vasp/firetasks/tests/test_polarization_to_db.py
atomate/vasp/submission_filter.py
requirements.txt
scripts/atwf
setup.py

Require minimum maggma version 0.39.0

---

.github/workflows/test.yml
README.md

Adds badges for
- CI status
- minimum supported Python version
- current PyPI release version
- monthly downloads from PyPI
Also fixes the broken logo on the [PyPI page](https://pypi.org/project/atomate):

Readme badges

---

atomate/vasp/firetasks/run_calc.py
atomate/vasp/fireworks/core.py

Related Custodian issue: https://github.com/materialsproject/custodian/issues/203.
Happy to add tests if this change is acceptable.

RunVaspCustodian add optional_param jobs: list[VaspJob]

---

atomate/vasp/firetasks/run_calc.py
atomate/vasp/fireworks/core.py

Revert the PR of "adding optional_param jobs: list[VaspJob]".
The original PR #742  is subjected to a review and will be reopened then.

Revert "RunVaspCustodian add optional_param jobs: list[VaspJob]"

---

.pre-commit-config.yaml
atomate/qchem/firetasks/critic2.py
atomate/qchem/workflows/tests/test_FF_and_critic.py
atomate/vasp/analysis/linear_response.py
atomate/vasp/builders/bandgap_estimation.py
atomate/vasp/firetasks/tests/test_copy.py
dev_scripts/plot_raman.py
setup.py

Follow up to #740.
Noticed that `atomate`'s PyPI page is still completely messed up because `setup.py` did not set
```py
long_description_content_type="text/markdown"
```

Fix PyPI page

---

.pre-commit-config.yaml
atomate/qchem/drones.py
atomate/utils/database.py
atomate/vasp/drones.py
atomate/vasp/workflows/base/adsorption.py
atomate/vasp/workflows/base/neb.py
dev_scripts/gibbs.py
setup.cfg

@Zhuoying Just ran a regex over the code base that removed repeated words.
CI is still failing atm but these are safe changes. Also Jimmy told me he fixed errors locally and will submit a PR for it soon.

Remove repeated words

---

atomate/vasp/database.py

Make sure that `obj_key` exists before trying to remove it from `calcs_reversed`

check for obj_key
